syntax on
highlight Normal ctermbg=black ctermfg=grey
highlight StatusLine term=none cterm=none ctermfg=black ctermbg=grey
highlight CursorLine term=none cterm=none ctermfg=none ctermbg=darkgrey
set number

set laststatus=2
set statusline=%F%r%h%= 


set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set clipboard=unnamedplus

filetype off
filetype plugin indent on

if expand("%:t") =~ ".*\.conf"
  set noexpandtab
  set tabstop=4
  set shiftwidth=4
endif

autocmd BufNewFile *.py :0r $HOME/.vim/template/python.py | :echo "Python Template read."
